config/routes.rb
Rails.application.routes.draw do
	get  'sales', to: 'sales#done'
	root 'sales#new'
	post 'add', to: 'sales#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
	validates :cod, uniqueness: true
	validates :detail, presence: true
	validates :category, inclusion: { in: %w(uno dos tres cuatro cinco), message: "%{value} is not a valid size" }
  	validates :value, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def done
    @sales = Sale.all
  end

  def new
    @sale = Sale.new
  end

  def create
  #	byebug
	@sale = Sale.new(sale_params)
	if @sale.tax == 1
      @sale.total = (1.19)*(@sale.value - @sale.value*@sale.discount/100)
    else
      @sale.total = @sale.value - @sale.value*@sale.discount/100
    end
	@sale.save
    redirect_to sales_path
  end 

  private
  def sale_params
    params.require(:sale).permit(:cod, :category, :detail, :value, :discount, :tax, :total)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E13CP1A1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/done.html.erb
<h1>Ventas</h1>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Lista de Ventas</div>

  <!-- Table -->
  <table class="table">
    <thead>
    <tr>
      <th>Cod</th>
      <th>Categoria</th>
      <th>Detail</th>
      <th>Category</th>
      <th>Value</th>
      <th>Discount</th>
      <th>Tax</th>
      <th>Total</th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.cod %></td>
		<td><%= sale.category %></td>
		<td><%= sale.detail %></td>
		<td><%= sale.value %></td>
		<td><%= sale.discount %></td>
		<td><%= sale.tax %></td>
		<td><%= sale.total %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>

<br>

app/views/sales/new.html.erb
<h1>Nueva Venta</h1>

  <div class="row justify-content-md-center col-md-10">
    <div class="col-md-5">
      <div class="row justify-content-md-center">
        <%= form_with model: @sale, url: add_path, local: true do |f| %>
        <div class="form-group col-md-10">
          <%= f.label :cod, "Código" %>
          <%= f.text_field :cod, class: 'form-control'%>
        </div>
        <div class="form-group col-md-10">
          <%= f. label :category%>
          <%= f.text_field :category, class: 'form-control'%>
        </div>
        <div class="form-group col-md-10">
          <%= f. label :detail, "Detalle" %>
          <%= f.text_area :detail, class: 'form-control'%>
        </div>
        <div class="form-group col-md-10">
          <%= f. label :value, "Value" %>
          <%= f.text_field :value, class: 'form-control'%>
        </div>
        <div class="form-group col-md-10">
          <%= f. label :discount, "% Descuento" %>
          <%= f.text_field :discount, class: 'form-control' %>
        </div>
        <div class="form-group col-md-5">
          <%= f. label :tax, "Con IVA" %>
          <%= f.check_box :tax %>
          <%= f.submit "Crear Venta", class: 'btn btn-primary' %>

        </div>
        <div class="form-group col-md-5">
          <%= link_to 'Volver', sales_path, class: 'btn btn-success' %>
        </div>
        <% end %>

      </div>
    </div>
  </div>